# GitHub Action Workflow for building the Ubuntu 22 images.

# SPDX-License-Identifier: BSD-2-Clause-Patent

name: "Ubuntu 24 Images"

# This workflow only runs (on the main branch or on PRs targeted
# at the main branch) and if files inside the Ubuntu-22 directory
# have been modifed/added/removed...

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Ubuntu-24/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Ubuntu-24/**'

jobs:
  Build_Image:
      uses: ./.github/workflows/build-image.yaml
      with:
        image_name: "Ubuntu-24"
        sub_images: "dev test build"
